import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/user/header';
import localFont from 'next/font/local';

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin'],
});

const diabloFont = localFont({
    src: [
        {
            path: '../fonts/DiabloStd.otf', // đường dẫn đến font
            weight: '400', // hoặc nhiều weight nếu có
            style: 'normal',
        },
    ],
    variable: '--font-diablo', // tạo CSS variable để dùng với Tailwind
});

export const metadata: Metadata = {
    title: 'Kkul-BBQ',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                suppressHydrationWarning
                className={`${montserrat.variable} ${diabloFont.variable} antialiased`}
            >
                <div className="">{children}</div>
            </body>
        </html>
    );
}
